name: iOS SwiftShare workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show versions
        run: |
          xcodebuild -version
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
          device: "iPhone 11"
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild clean build-for-testing -scheme "$scheme" -destination "platform=$platform,name=$device"
      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
          device: "iPhone 11"
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild test-without-building -scheme "$scheme" -destination "platform=$platform,name=$device"
